version: "3.8"

x-node-env: &node-env
    image: node:16.8.0
    user: node
    ports:
        - "8080:8000"
    volumes:
        - .:/app
    working_dir: "/app"
    environment:
        TZ: "Europe/Prague"

services:
    node-app:
        <<: *node-env
        command: |
            bash -c "
                sleep 3 &&
                npm ci &&
                npm start
            "
